import BANNER_1 from './BANNER_1.webp'
import BANNER_2 from './BANNER_2.webp'
import BANNER_3 from './BANNER_3.webp'
import BANNER_4 from './BANNER_4.webp'
import CARTAO_AMIGO_SAUDE from './CARTAO_AMIGO_SAUDE.webp'
import DESCONTO from './DESCONTO.webp'
import DROGA_RAIA from './DROGA_RAIA.webp'
import DROGAL from './DROGAL.png'
import FAMILIA_REUNIDA from './FAMILIA_REUNIDA.webp'
import FUNDO_REMEDIOS from './FUNDO_REMEDIOS.webp'
import ICONE_AMERICAN_EXPRESS from './ICONE_AMERICAN_EXPRESS.webp'
import ICONE_AMPLA_REDE from './ICONE_AMPLA_REDE.webp'
import ICONE_DENTE from './ICONE_DENTE.webp'
import ICONE_DINERS_CLUB from './ICONE_DINERS_CLUB.webp'
import ICONE_ELO from './ICONE_ELO.webp'
import ICONE_EMPRESTIMO from './ICONE_EMPRESTIMO.webp'
import ICONE_HIPERCARD from './ICONE_HIPERCARD.webp'
import ICONE_INFINITO from './ICONE_INFINITO.webp'
import ICONE_MASTERCARD from './ICONE_MASTERCARD.webp'
import ICONE_PLANO_SAUDE from './ICONE_PLANO_SAUDE.webp'
import ICONE_PRONTO_ATENDIMENTO from './ICONE_PRONTO_ATENDIMENTO.webp'
import ICONE_REMEDIO from './ICONE_REMEDIO.webp'
import ICONE_SEGURO_VIDA from './ICONE_SEGURO_VIDA.webp'
import ICONE_VISA from './ICONE_VISA.webp'
import ICONE_WHATSAPP from './ICONE_WHATSAPP.webp'
import IDOSA_COM_CELULAR from './IDOSA_COM_CELULAR.webp'
import LOGO_MAO_AMIGA from './LOGO_MAO_AMIGA.webp'
import MEDICOS_COM_REMEDIO from './MEDICOS_COM_REMEDIO.webp'
import LOGO from './LOGO.webp'
import PRECO from './PRECO.webp'
import MULHER_COM_CELULAR from './MULHER_COM_CELULAR.webp'
import HOMEM_COM_CELULAR from './HOMEM_COM_CELULAR.webp'
import MULHER_CACHEADA_CELULAR from './MULHER_CACHEADA_CELULAR.webp'
import CRIANCA_NA_GRAMA from './CRIANCA_NA_GRAMA.webp'
import FUNCIONARIOS_REUNIDOS from './FUNCIONARIOS_REUNIDOS.webp'
import HOMEM_SERIO from './HOMEM_SERIO.webp'
import ADESAO from './ADESAO.jpg'
import INTRANET from './INTRANET.jpg'
import MULHER_SERIA from './MULHER_SERIA.webp'
import PAI_COM_FILHO from './PAI_COM_FILHO.webp'
import ICONE_VISAO from './ICONE_VISAO.webp'
import ICONE_WEBMAIL from './ICONE_WEBMAIL.png'
import MAE_SEGURANDO_BEBE from './MAE_SEGURANDO_BEBE.webp'
import MAO_SEGURANDO_DADOS from './MAO_SEGURANDO_DADOS.jpg'
import ICONE_MISAO from './ICONE_MISAO.webp'
import ICONE_GALAX from './ICONE_GALAX.png'
import ICONE_PESSOAS from './ICONE_PESSOAS.png'
import CELULAR_APP_CARTAO from './CELULAR_APP_CARTAO.webp'
import ICONE_DIAMANTE from './ICONE_DIAMANTE.webp'
import DOIS_MEDICOS from './DOIS_MEDICOS.webp'
import EMPRESARIO_COM_CELULAR from './EMPRESARIO_COM_CELULAR.webp'
import MULHER_FELIZ_COM_CELULAR from './MULHER_FELIZ_COM_CELULAR_.webp'
import MULHER_TRABALAHANDO_COM_CELULAR from './MULHER_TRABALAHANDO_CELULAR.webp'
import PESSOA_OLHANDO_PRA_VOCE from './PESSOA_OLHANDO_PRA_VOCÊ.webp'
import IMAGEM_EM_BRANCO from './IMAGEM_EM_BRANCO.png'
import REGULAMENTOS from './REGULAMENTOS.jpg'
import FUNCIONARIOS_CONVERSANDO from './FUNCIONARIOS_CONVERSANDO.webp'
import BANNER_ATENDIMENTO from './BANNER_ATENDIMENTO.webp'
import ACORDO from './ACORDO.webp'
import ASSISTENCIA_FUNERAL from './ASSISTENCIA_FUNERAL.webp'
import FAMIALIA_REUNIDA_BRANCOS from './FAMILIA_REUNIDA_BRANCOS.webp'
import CRM from './CRM.png'
import BENEFICIOS from './BENEFICIOS.avif'
import BENEFICIOS_MORENA from './BENEFICIOS_MORENA.avif'
import DISCOUNT from './discount.png'
import ACCIDENT from './accident.png'
import LAMINA from './LAMINA.jpg'
import BENEFICIOS_CARTAO from './BENEFICIOS_CARTAO.avif'
import DOIS_HOMENS_ACORDO from './DOIS_HOMENS_ACORDO.avif'
import FUNERAL from './ASSISTENCIA_FUNERAL.avif'
import EMPRESTIMO_EQUIPAMENTOS from './EMPRESTIMO_EQUIPAMENTOS.avif'
import SEGURO_DE_VIDA from './SEGURO_DE_VIDA.avif'
import TELEMEDICINA_MULHER from './TELEMEDICINA_MULHER.avif'
import MEDICAMENTOS from './MEDICAMENTOS.avif'
import ALLAN from './ALLAN.jpeg'
import TAG from './tag.png'
import CLUBE_CERTO from './CLUBE_CERTO.avif'
import BOTAO_APPLE from './BOTAO_APPLE.png'
import BOTAO_GOOGLE from './BOTAO_GOOGLE.png'

const IMAGE = {
  BOTAO_APPLE,
  BOTAO_GOOGLE,
  CLUBE_CERTO,
  ALLAN,
  TAG,
  BENEFICIOS_CARTAO,
  FUNERAL,
  EMPRESTIMO_EQUIPAMENTOS,
  SEGURO_DE_VIDA,
  TELEMEDICINA_MULHER,
  MEDICAMENTOS,
  DOIS_HOMENS_ACORDO,
  LAMINA,
  DISCOUNT,
  ACCIDENT,
  BENEFICIOS,
  BENEFICIOS_MORENA,
  CRM,
  FAMIALIA_REUNIDA_BRANCOS,
  PESSOA_OLHANDO_PRA_VOCE,
  IMAGEM_EM_BRANCO,
  REGULAMENTOS,
  FUNCIONARIOS_CONVERSANDO,
  BANNER_ATENDIMENTO,
  ACORDO,
  ASSISTENCIA_FUNERAL,
  EMPRESARIO_COM_CELULAR,
  MULHER_FELIZ_COM_CELULAR,
  MULHER_TRABALAHANDO_COM_CELULAR,
  DOIS_MEDICOS,
  ICONE_DIAMANTE,
  BANNER_1,
  BANNER_2,
  BANNER_3,
  BANNER_4,
  CARTAO_AMIGO_SAUDE,
  DESCONTO,
  DROGA_RAIA,
  DROGAL,
  FAMILIA_REUNIDA,
  FUNDO_REMEDIOS,
  ICONE_AMERICAN_EXPRESS,
  ICONE_AMPLA_REDE,
  ICONE_DENTE,
  ICONE_DINERS_CLUB,
  ICONE_ELO,
  ICONE_EMPRESTIMO,
  ICONE_HIPERCARD,
  ICONE_INFINITO,
  ICONE_MASTERCARD,
  ICONE_PLANO_SAUDE,
  ICONE_PRONTO_ATENDIMENTO,
  ICONE_REMEDIO,
  ICONE_SEGURO_VIDA,
  ICONE_VISA,
  ICONE_WHATSAPP,
  IDOSA_COM_CELULAR,
  LOGO_MAO_AMIGA,
  MEDICOS_COM_REMEDIO,
  LOGO,
  PRECO,
  MULHER_COM_CELULAR,
  HOMEM_COM_CELULAR,
  MULHER_CACHEADA_CELULAR,
  CRIANCA_NA_GRAMA,
  FUNCIONARIOS_REUNIDOS,
  HOMEM_SERIO,
  ADESAO,
  INTRANET,
  MULHER_SERIA,
  PAI_COM_FILHO,
  ICONE_VISAO,
  ICONE_WEBMAIL,
  MAE_SEGURANDO_BEBE,
  MAO_SEGURANDO_DADOS,
  ICONE_MISAO,
  ICONE_GALAX,
  ICONE_PESSOAS,
  CELULAR_APP_CARTAO,
}

export default IMAGE
